[project]
name = "capslap-pyside"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Olli Sulopuisto", email = "1051255+ollisulopuisto@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "psutil>=7.2.2",
    "pyside6>=6.11.2",
    "pytest>=9.1.1",
    "pytest-qt>=4.5.0",
]

[project.scripts]
capslap = "app.main:main"

[build-system]
requires = ["uv_build>=0.12.12,<0.13.0"]
build-backend = "uv_build"

[tool.pytest.ini_options]
pythonpath = ["."]

